export enum Roles {
  WORKSPACE_ADMIN = 'WORKSPACE_ADMIN',
  CHANNEL_ADMIN = 'CHANNEL_ADMIN',
  PREVILEDGE_USER = 'PREVILEDGE_USER',
  USER = 'USER',
}

export const ALL_ROLES = [
  Roles.WORKSPACE_ADMIN,
  Roles.CHANNEL_ADMIN,
  Roles.PREVILEDGE_USER,
  Roles.USER,
];
