export enum ROLES {
  WORKSPACE_ADMIN = 'WORKSPACE_ADMIN',
  CHANNEL_ADMIN = 'CHANNEL_ADMIN',
  WORKSPACE_PRIVILEDGE_MEMBER = 'WORKSPACE_PRIVILEDGE_MEMBER',
  WORKSPACE_MEMBER = 'WORKSPACE_MEMBER',
  CHANNEL_MEMBER = 'CHANNEL_MEMBER',
}

export const ALL_ROLES = [
  ROLES.WORKSPACE_ADMIN,
  ROLES.CHANNEL_ADMIN,
  ROLES.WORKSPACE_PRIVILEDGE_MEMBER,
  ROLES.WORKSPACE_MEMBER,
  ROLES.CHANNEL_MEMBER,
];
